### ISSUE TITLE
white webpage

### ISSUE THREAD

**Issue by lucianm** [mariolukas/HydraPlay#16]
Hello,

as I too once saw Ryan's video on YT, I was pleasantly surprised someone got the idea further and published code. I already had a proof of concept snapcast/mopidy setup installed on my DIY NAS running OMV4 (Debian Stretch) on amd64 without pulseaudio, and it works well with Android snapclients. Once I stumbled upon HydraPlay, of course I wanted that. I modified my setup a little bit by following the instructions in the README (installed & configured everything), streaming still works, I now have multile mopidy instances running on different ports, started by separate systemd units. As of HydraPlay, my understanding was to checkout the sources and give websockify the -web argument pointing to the src subfolder of HydraPlay (only that one contains an index.html, any other will just list the directory contents). Pointing any browser to the LAN address on port 8080 will just load a white page, which shows the source of index.html if I right-click to see the web page source. Some browsers even show the Angular favicon.

What could be wrong, where to look for some logs, how to debug?

**Comment by mariolukas** [comment]
Are there errors in the Browsers JavaScript console?

**Comment by mariolukas** [comment]
One more thing. You need to build HydraPlay before you place the files into `/home/pi/hydraplay`

1. Install node on the pi or on your local machine
2. change to the HydraPlay Source folder.
3. Install dependencies with `npm install`
4. change the ip and ports in `environment.ts`
5. Build with ng build
6. the result will be in `target/build`
7. copy all files in `target/build`  to `/home/pi/hydraplay` on the pi
8. try to connect.

**Comment by lucianm** [comment]
Thanks Mario, I didn't understand until now that I have to install nodejs, did it with v10.16.0 and followed your instructions, found the build under dist/multiroom-snapcast-gui. Now if I serve that in websockify, I can see the "zones", can even control play/pause, volume and mute buttons from hydraplay (the react instantly in the Android client fr example), but I cannot search for or select a stream to be played.

**Comment by mariolukas** [comment]
Sounds good. One more thing. Do you have the tune in plugin activated in the mopidy configs?
Add this to the config. 
`[tunein]
timeout = 5000`

**Comment by mariolukas** [comment]
I just checked my installation. What is the exact behavior 

1. when you click on the cover icon on the player. 
2. when you type in some search expressions like "your favorite radio station"
3. after a short moment you should see a list of covers appearing below the search input field.
4. ( That is where the tricky part comes in due to a bug, first run and so on...) you need to select one of the mopidy streams, the icons upon the search result, you will be returned to the players. 
5. click again on the cover image, and finally select your radio station. 
( After you selected it once for a running server it will work from there. I had not the time to work on it since I created the player 3 month ago.)
6. the stream should start. but be patient mostly there will be a commercial before the stream starts and this commercial is played with a delay. This is on tunein so we can nothing do against this issue :)

The description is the expected behaviour and how it works for my setup.

**Comment by mariolukas** [comment]
>I didn't understand until now that I have to install nodejs

Yes. I know.  NodeJS is only needed to build the packages. I should provide a release where all the files of the current player are ready to use. More over a docker, ready to use image or maybe an install script would be the best. 

Hopefully some people with programming skills will join this project, because this is just a fun project for me, due I am working most of my spare time on the [ https://fabscan.org ]( http://fabscan.org project.)

**Comment by lucianm** [comment]
Oh, a docker image would be awesome.
So I had issues with pulseaudio blocking the fifos, mopidy could not write to them, therefore I deactivated them an let snapcast create them. Then I noticed my mopidy installation was outdated, now I installed the latest one. I can listen to local media, stream from TuneIn, SoundCloud, Google Play Music, but all when selected, browsed explicitely from the mopidy web GUI, but I cannot search in HydraPlay, or Mopidy itself for something, although in the mopidy log I can see the search is passed to the different sources...

**Comment by MrSliff** [comment]
Hey mate,

i wanted to try your GUI for multiroom Audio.

Unfortunately i cannot build with "ng build". Nothing happens.

Can you give me an advise?

**Comment by mariolukas** [comment]
I have created a docker image for development on a local host. Running Docker on a Raspberry Pi with all those network components was painful. I ended up in creating a setup bash scrit. This script can be used on Rasbian, it will do the whole configuration. 
https://github.com/mariolukas/HydraPlay/tree/master/hydracontrol
