### ISSUE TITLE
Add better documentation about how it works

### ISSUE THREAD

**Issue by k4kfh** [mariolukas/HydraPlay#9]
This is a very interesting project to me because it seems like one of the few attempts to make a single cohesive control system for Snapcast and actual audio sources (Spotify, Google Music, etc). I've toyed with the idea of building something similar, just haven't found the time, so I'm intrigued with this project. But it's not clear to me how it works. Does HydraPlay spawn a new Snapcast server instance for each new source? Does it create new streams within a single Snapcast server (and if so, how, since the current JSON API doesn't support that)? Some kind of step-by-step documentation of a typical use case would be a big help in understanding how all these different projects interface with one another. Laid out like this:

| User Space            | Under the Hood                                     |
|-----------------------|----------------------------------------------------|
| Some action in the UI | What actually happens with Snapserver, Mopidy, etc |

**Comment by mariolukas** [comment]
First of all thank you for your commitment. 

You are right, it needs a better documentation. This project is in a very early stage but it works like a charm and I am using it for months now. Anyway I am writing a Blog post where the whole concept will be described but I had not the time to finish it until now. 

There is only one SnapCast Server. And multiple SnapClients. The Server and each client are running on one machine (in my example a raspberry pi). Each client it used for one "zone" (living room, bathroom, bedroom, etc. ...). In my case I am using three clients. Kitchen, living room and bathroom, that makes three Raspberry Pi's and one more for the server. Each of the SanpClient Pis has an audio amplification HAT on top. 

The Client Raspberry's are only running the SnapCast Client software. The Raspberry Pi used for the server runs SnapCast Server, Pulseaudio and one Mopidy isnstance for each stream. A stream can deliver audio from different sources. 

There are a lot of Mopidy plugins. E.g. Spotify, TuneIn, Youtube.... With those Plug-Ins each Mopidy instance (stream) is able to deliver an audio stream from those sources to the wanted SnapCast client.

By now there is no option to spawn new Mopidy instances on the fly. But this would be a really cool feature. 

The JSON API of SnapCast is more or less only used for two reasons. One is changing the Volume and the other One is switching between the streams. Which stream will be attached to which client (It is also possible to attache one stream to multiple clients).

The JSON API of Mopidy is used to control the streams/mopidy instances. That means starting, stopping the stream and searching and selecting of tracks etc.

I hope this helps a little bit to understand how the things interact. I know that there is a lot of potential for additional features. I had not the time to do additional work since I pushed the latest commits.

**Comment by k4kfh** [comment]
Thank you, that helps a lot. I'll try to put together a PR that incorporates this explanation into the README, because I think it'll help potential users understand what's actually going on.

> By now there is no option to spawn new Mopidy instances on the fly. But this would be a really cool feature. The JSON API of SnapCast is more or less only used for two reasons. One is changing the Volume and the other One is switching between the streams. Which stream will be attached to which client (It is also possible to attache one stream to multiple clients).

Ideally, I would say the end goal should be to have an unlimited number of Mopidy instances which are spawned/destroyed on the fly. This requires one crucial feature: the ability to create and delete streams via the Snapserver JSON API. There is currently a PR up on Snapcast's repo that adds this feature, although it hasn't been merged and still needs a little cleanup to be production-ready IMO. But I think this is what you/we should aim for in the future, because that makes the system infinitely expandable, and doesn't require nearly the same complex setup as manually creating a million Mopidy instances. It also means you could add a Snapclient on the fly without any mucking about with reconfiguration and new Mopidy instances.

I understand that's a big refactor to do things that way, just thought I'd offer that as a suggestion for the future. I'm hoping over the next few months Snapcast gets a little more active development...I feel like it's very close to being extremely powerful, but it needs a couple more little features added to make it feasible for wrappers like HydraPlay to manipulate it.

**Comment by mariolukas** [comment]
> I understand that's a big refactor to do things that way, just thought I'd offer that as a suggestion for >the future. I'm hoping over the next few months Snapcast gets a little more active development...I feel >like it's very close to being extremely powerful, but it needs a couple more little features added to >make it feasible for wrappers like HydraPlay to manipulate it.

I am completely open for new features.

**Comment by mariolukas** [comment]
There is a bash script for initial setup, now.
